import {Dimensions, StyleSheet} from 'react-native';
const deviceSize = Dimensions.get('window');

export const styles = StyleSheet.create({
  modalContainer: {
    justifyContent: 'flex-end',
    margin: 0,
  },
  innerContainer: {
    backgroundColor: '#FFFFFF',
    borderTopLeftRadius: 10,
    borderTopRightRadius: 10,
    height: deviceSize.height / 2,
    padding: 10,
  },
  title: {
    color: 'black',
    textAlign: 'left',
    fontSize: 20,
    fontWeight: 'bold',
    marginBottom: 20,
  },
  timeBtn: {
    height: 50,
    width: '100%',
    borderWidth: 1,
    borderRadius: 10,
    justifyContent: 'center',
    alignItems: 'flex-start',
    paddingLeft: 10,
    borderColor: '#f2f2f2',
    marginBottom: 10,
    backgroundColor: 'white',
    shadowOffset: {width: 0, height: 0},
    shadowRadius: 2,
    elevation: 2,
    shadowOpacity: 0.3,
    marginTop: 5,
  },
  btnText: {
    fontSize: 15,
    fontWeight: '500',
    color: '#3c4248',
  },
  inputTitle: {
    borderWidth: 1,
    borderRadius: 10,
    borderColor: '#f2f2f2',
    color: 'black',
    height: 50,
    paddingLeft: 10,
    backgroundColor: 'white',
    shadowOffset: {width: 0, height: 0},
    shadowRadius: 2,
    elevation: 2,
    shadowOpacity: 0.3,
    marginTop: 5,
  },
  inputTask: {
    borderRadius: 10,
    borderColor: '#f2f2f2',
    marginTop: 6,
    color: 'black',
    height: '100%',
    flex: 1,
  },
  buttonContainer: {
    backgroundColor: '#77B9FF',
    borderRadius: 8,
    justifyContent: 'center',
    alignItems: 'center',
    marginTop: 15,
    padding: 12,
    height: 50,
  },
  buttonPlaceHolder: {
    color: 'black',
    fontSize: 18,
    fontWeight: '400',
  },
  textInputStyle: {
    height: 70,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    borderRadius: 10,
    paddingHorizontal: 10,
    backgroundColor: 'white',
    shadowOffset: {width: 0, height: 0},
    shadowRadius: 2,
    elevation: 2,
    shadowOpacity: 0.3,
    borderColor: '#f2f2f2',
    marginTop: 10,
  },
  errorText: {
    marginLeft: 8,
    marginTop: 5,
    color: '#E74C3C',
    fontSize: 12,
  },
  errorTime: {
    marginLeft: 8,
    color: '#E74C3C',
    fontSize: 12,
  },
});
